#!/bin/sh
# Install all dependencies for running in development mode.

set -e
cd "$(dirname "$0")/.."

echo "==> Installing gem dependencies..."
bundler version &>/dev/null || {
  gem install bundler --no-rdoc --no-ri
}

bundle check &>/dev/null || {
  bundle install --without production
}
bundle clean
