#!/bin/sh

# script/bootstrap: Install all dependencies for running in
#   development mode.

set -e
cd "$(dirname "$0")/.."

echo "==> Installing gem dependencies..."
bundler version 2>&1 >/dev/null || {
  gem install bundler --no-rdoc --no-ri
}
bundle install --path .bundle --without production
