#!/bin/sh
# Launch the application and required processes.
# If RACK_ENV is set, start the given environment, else in development.

set -e
cd "$(dirname "$0")/.."

# update everything
script/update

test -z "$RACK_ENV" && RACK_ENV='development'

echo "==> Starting APP in $RACK_ENV environment..."
if [ "$RACK_ENV" == "production" ]; then
  bundle exec thin start -C config/thin.yml -p 13051
else
  bundle exec shotgun -o 0.0.0.0 -p 4567 -u /ehgp-dev
fi
