#!/bin/sh

# script/server: Launch the application and any extra required processes

set -e
cd "$(dirname "$0")/.."

# update everything
script/update

test -z "$RACK_ENV" && RACK_ENV='development'

echo "==> Starting APP in $RACK_ENV environment..."
if [ "$RACK_ENV" == "production"]; then
  bundle exec thin start -C config/thin.yml -p 13051
else
  shotgun -o 0.0.0.0 -p 4567 -u /ehgp-dev
fi
