#!/bin/sh
# Set up the application for the first time.
# - install dependencies
# - create required config files

set -e
cd "$(dirname "$0")/.."

script/bootstrap

echo "==> check DB config..."
test -f config/database.yml || {
  cp config/database.example.yml config/database.yml
  $EDITOR config/database.yml
}
